ALTER TABLE public.settings
ADD COLUMN IF NOT EXISTS fedex_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS fedex_use_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS fedex_api_key text,
ADD COLUMN IF NOT EXISTS fedex_secret_key text,
ADD COLUMN IF NOT EXISTS fedex_child_key text,
ADD COLUMN IF NOT EXISTS fedex_child_secret text,
ADD COLUMN IF NOT EXISTS fedex_account_number text,
ADD COLUMN IF NOT EXISTS fedex_meter_number text,
ADD COLUMN IF NOT EXISTS fedex_default_service_type text DEFAULT 'FEDEX_GROUND',
ADD COLUMN IF NOT EXISTS fedex_default_packaging_type text DEFAULT 'YOUR_PACKAGING',
ADD COLUMN IF NOT EXISTS fedex_default_pickup_type text DEFAULT 'USE_SCHEDULED_PICKUP',
ADD COLUMN IF NOT EXISTS fedex_label_stock_type text DEFAULT 'PAPER_85X11_TOP_HALF_LABEL',
ADD COLUMN IF NOT EXISTS fedex_label_image_type text DEFAULT 'PDF',
ADD COLUMN IF NOT EXISTS fedex_default_weight_value numeric(10,2) DEFAULT 1,
ADD COLUMN IF NOT EXISTS fedex_default_weight_units text DEFAULT 'LB',
ADD COLUMN IF NOT EXISTS fedex_default_length numeric(10,2) DEFAULT 12,
ADD COLUMN IF NOT EXISTS fedex_default_width numeric(10,2) DEFAULT 10,
ADD COLUMN IF NOT EXISTS fedex_default_height numeric(10,2) DEFAULT 8,
ADD COLUMN IF NOT EXISTS fedex_default_dimension_units text DEFAULT 'IN';
