// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://cfyqeilfmodrbiamqgme.supabase.co";
// const SUPABASE_URL = "https://wrvmbgmmuoivsfancgft.supabase.co";
//9RX DB
// const SUPABASE_URL = "https://qiaetxkxweghuoxyhvml.supabase.co";

// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeXFlaWxmbW9kcmJpYW1xZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMzU1MzUsImV4cCI6MjA1MTkxMTUzNX0.iQNaVfII5iplmoH-acTf50VHm3YDue9XCHvHas4vMOA";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indydm1iZ21tdW9pdnNmYW5jZ2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzIzMTcsImV4cCI6MjA3ODYwODMxN30.qtTYnhBes4nd7n_kDH_S3HxS7Zl0pf1JW708wOJ7e08";

//9RX DB - US West
export const SUPABASE_URL = "https://qiaetxkxweghuoxyhvml.supabase.co";
//9RX DB - US West
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYWV0eGt4d2VnaHVveHlodm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTM1MzMsImV4cCI6MjA4NjkyOTUzM30.LqjfwdltknPXai8oEBALGpl7nLIxDp4YB9yO3G7O37E";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isSupabaseAuthKey = (key: string) => key.startsWith("sb-") && key.includes("auth-token");

const readCookie = (name: string): string | null => {
  const encodedName = encodeURIComponent(name) + "=";
  const parts = document.cookie.split("; ");
  for (const part of parts) {
    if (part.startsWith(encodedName)) {
      return decodeURIComponent(part.slice(encodedName.length));
    }
  }
  return null;
};

const writeSessionCookie = (name: string, value: string) => {
  // No Expires/Max-Age => session cookie (clears on browser close)
  document.cookie = `${encodeURIComponent(name)}=${encodeURIComponent(value)}; path=/; SameSite=Lax`;
};

const removeCookie = (name: string) => {
  document.cookie = `${encodeURIComponent(name)}=; path=/; Max-Age=0; SameSite=Lax`;
};

export const hasPersistedSupabaseSession = (): boolean => {
  const hasSessionStorage = Object.keys(window.sessionStorage).some(isSupabaseAuthKey);
  if (hasSessionStorage) return true;

  // Keep backward compatibility for any old localStorage sessions.
  const hasLegacyLocalStorage = Object.keys(window.localStorage).some(isSupabaseAuthKey);
  if (hasLegacyLocalStorage) return true;

  return document.cookie
    .split("; ")
    .some((part) => {
      const [rawName] = part.split("=");
      if (!rawName) return false;
      const key = decodeURIComponent(rawName);
      return isSupabaseAuthKey(key);
    });
};

export const clearPersistedSupabaseSession = () => {
  Object.keys(window.sessionStorage).forEach((key) => {
    if (key.startsWith("sb-") || key.includes("supabase")) {
      window.sessionStorage.removeItem(key);
    }
  });

  Object.keys(window.localStorage).forEach((key) => {
    if (key.startsWith("sb-") || key.includes("supabase")) {
      window.localStorage.removeItem(key);
    }
  });

  document.cookie.split("; ").forEach((part) => {
    const [rawName] = part.split("=");
    if (!rawName) return;
    const key = decodeURIComponent(rawName);
    if (key.startsWith("sb-") || key.includes("supabase")) {
      removeCookie(key);
    }
  });
};

// Custom storage adapter:
// - sessionStorage for fast same-tab access
// - session cookie for cross-tab + browser-close expiry behavior
const customStorage = {
  getItem: (key: string) => {
    return window.sessionStorage.getItem(key) || readCookie(key);
  },
  setItem: (key: string, value: string) => {
    window.sessionStorage.setItem(key, value);
    writeSessionCookie(key, value);
    // Remove legacy persistent entry if it exists.
    window.localStorage.removeItem(key);
  },
  removeItem: (key: string) => {
    window.sessionStorage.removeItem(key);
    window.localStorage.removeItem(key);
    removeCookie(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
