// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://cfyqeilfmodrbiamqgme.supabase.co";
// const SUPABASE_URL = "https://wrvmbgmmuoivsfancgft.supabase.co";
//9RX DB
// const SUPABASE_URL = "https://qiaetxkxweghuoxyhvml.supabase.co";

// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeXFlaWxmbW9kcmJpYW1xZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMzU1MzUsImV4cCI6MjA1MTkxMTUzNX0.iQNaVfII5iplmoH-acTf50VHm3YDue9XCHvHas4vMOA";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indydm1iZ21tdW9pdnNmYW5jZ2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzIzMTcsImV4cCI6MjA3ODYwODMxN30.qtTYnhBes4nd7n_kDH_S3HxS7Zl0pf1JW708wOJ7e08";

//9RX DB - US West
export const SUPABASE_URL = "https://qiaetxkxweghuoxyhvml.supabase.co";
//9RX DB - US West
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYWV0eGt4d2VnaHVveHlodm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTM1MzMsImV4cCI6MjA4NjkyOTUzM30.LqjfwdltknPXai8oEBALGpl7nLIxDp4YB9yO3G7O37E";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter that uses sessionStorage but allows magic links to work
const customStorage = {
  getItem: (key: string) => {
    // Check both storages for flexibility
    return window.sessionStorage.getItem(key) || window.localStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    // Store in sessionStorage for browser-close logout
    window.sessionStorage.setItem(key, value);
    // Also temporarily in localStorage for magic link flow
    window.localStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    window.sessionStorage.removeItem(key);
    window.localStorage.removeItem(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
